{
 "title": "Gatling Lite",
 "tags": [ "Gatling" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "db", "label": "db", "query": "influxdb" },
   { "name": "Prefix", "label": "Prefix", "query": "show measurements" },
   {
    "name": "percentiles",
    "label": "percentiles",
    "query": "min,percentiles50,percentiles75,percentiles95,percentiles99,max"
   }
  ]
 },
 "panels": [
  { "title": "Текущие значения", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Indicators",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "alias": "t < 800 ms",
     "measurement": "gatling",
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" <= 800 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "800 ms < t < 1200 ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" > 800 and \"mean\" <= 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "t > 1200ms",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"mean\" > 1200 and \"status\" = 'ok' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "failed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE $timeFilter and \"status\" = 'ko' and \"request\" = 'allRequests'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT last(\"active\") FROM /^$Prefix.users$/ WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Current RPS",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Prefix$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total OK",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "Total KO",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT sum(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'ko') AND $timeFilter  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  { "title": "Запросы", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Response time by Request ($percentiles)",
   "type": "graph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "request" ], "type": "tag" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT mean(\"$percentiles\") FROM /^$Prefix$/ WHERE (\"request\" <> 'allRequests') AND $timeFilter GROUP BY time($__interval), \"request\"",
     "select": [
      [
       { "params": [ "$percentiles" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "request", "operator": "<>", "value": "allRequests" }
     ]
    }
   ]
  },
  {
   "title": "Errors vs. Passes",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Total requests ($tag_simulation)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'all') AND $timeFilter  GROUP BY time($__interval), \"simulation\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Total pass ($tag_simulation)",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT mean(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'ok') AND $timeFilter  GROUP BY time($__interval), \"simulation\"\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "Total error ($tag_simulation)",
     "fields": [
      { "func": "mean", "name": "value" }
     ],
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "/^$Prefix$/",
     "query": "SELECT mean(\"count\") FROM /^$Prefix$/ WHERE (\"request\" = 'allRequests' AND \"status\" = 'ko') AND $timeFilter  GROUP BY time($__interval), \"simulation\"\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "status", "operator": "=", "value": "ko" }
     ]
    }
   ]
  }
 ]
}